services:
  - name: docker:19.03.13-dind

include:
  - https://raw.githubusercontent.com/getindata/gitlab_cicd_templates/v0.1.14/dataops/gcp/gcp_setup_template.yml
  - https://raw.githubusercontent.com/getindata/gitlab_cicd_templates/v0.1.14/dataops/cicd_template.yml

variables:
  DOCKER_REGISTRY: europe-central2-docker.pkg.dev
  BLOB_CONFIG_PATH: blob_args.json
  GCP_PROJECT: $GCP_PROJECT

stages:
  - execute-dev
  - execute-release
